---
- name: Install and Configure Certbot SSL
  hosts: gateway
  become: true

  tasks:
    - name: Install Certbot and python3-certbot-nginx
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: true

    - name: Generate SSL Certificates with Certbot
      ansible.builtin.command: >
        certbot --nginx --non-interactive --agree-tos -m adiwiajaya.jy@gmail.com
        -d exporter-adiwijaya.studentdumbways.my.id
        -d monitoring-adiwijaya.studentdumbways.my.id
        -d prom-adiwijaya.studentdumbways.my.id
      args:
        creates: /etc/letsencrypt/live/adiwijaya.studentdumbways.my.id/fullchain.pem
